# Generated by Django 5.1.6 on 2025-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nagranie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik_audio', models.FileField(upload_to='nagrania/')),
                ('transkrypcja', models.TextField(blank=True, null=True)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
